name: Clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Shader Compilation Toolchain
      run: rustup toolchain install nightly-2023-05-27 && rustup +nightly-2023-05-27 component add rust-src rustc-dev llvm-tools-preview clippy

    - name: Sample Plugin
      run: cd sample-plugin && cargo clippy --all-targets --all-features

    - name: Shader Compiler
      run: cd tools/thorn-shader-compiler && cargo clippy --all-targets --all-features
    
    - name: Thorn-GE
      run: cd thorn-ge && cargo clippy --all-targets --all-features
