
name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Shader Compilation Toolchain
      run: rustup toolchain install nightly-2023-05-27 && rustup +nightly-2023-05-27 component add rust-src rustc-dev llvm-tools-preview

    - name: Build
      run: cd thorn-ge && cargo build --verbose
      
    - name: Test
      run: cd thorn-ge && cargo test --verbose
